#!/bin/zsh

set -e

METAL_FILE="Sources/Upscaling/Shaders/Sharpen.metal"
SWIFT_FILE="Sources/Upscaling/Shaders/SharpenShader.swift"

if [ ! -f "$SWIFT_FILE" ] || [ "$METAL_FILE" -nt "$SWIFT_FILE" ]; then
    echo "Generate $SWIFT_FILE from $METAL_FILE..."

# Read the content of the Metal file and embed it into the Swift file.
cat > "$SWIFT_FILE" <<EOF
import Foundation

// This file is automatically generated by the build.sh script.
// Do not edit this file directly; instead, edit Sharpen.metal.

enum Shaders {
    static let sharpenLuma = """
$(cat "$METAL_FILE")
"""
}
EOF

    echo "$SWIFT_FILE was successfully generated."
fi

echo "Start Swift Build..."
swift build "$@"

echo "Build finished."
